name: workflow example
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: node /Users/Salmaais job's status is ${{ job.status }}."n/Documents/Mejhool_NodeJS/server.js 

